### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by ghost** [cvortmann/git-anonymize#2]
```bash
  git clone https://github.com/cvortmann/git-anonymize.git
  cd git-anonymize
  make install
 ```
still couldn't add anonymize as a sub command.
has anything changed?

**Comment by cvortmann** [comment]
@lkiran5080 sorry, just saw this. Yes, it's working. It's installed at `$HOME/bin`, so make sure that's in your path. Let me know if you able to use it.
